// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_1KLpIylBI7osRpjJEkC9cM5gN8B_3U0',
    appId: '1:661935203684:web:0b9f94e00d41ba9a9c0671',
    messagingSenderId: '661935203684',
    projectId: 'authexample-1-4b596',
    authDomain: 'authexample-1-4b596.firebaseapp.com',
    storageBucket: 'authexample-1-4b596.firebasestorage.app',
    measurementId: 'G-5JMB68BPH1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfrqXHeLfKuXKEWT02DO8oQUN5sVMgFBI',
    appId: '1:661935203684:ios:a0a031b6c6300e2b9c0671',
    messagingSenderId: '661935203684',
    projectId: 'authexample-1-4b596',
    storageBucket: 'authexample-1-4b596.firebasestorage.app',
    iosClientId: '661935203684-kknqt2oje3e4glp6u104gnlen4hovu4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfrqXHeLfKuXKEWT02DO8oQUN5sVMgFBI',
    appId: '1:661935203684:ios:a0a031b6c6300e2b9c0671',
    messagingSenderId: '661935203684',
    projectId: 'authexample-1-4b596',
    storageBucket: 'authexample-1-4b596.firebasestorage.app',
    iosClientId: '661935203684-kknqt2oje3e4glp6u104gnlen4hovu4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_1KLpIylBI7osRpjJEkC9cM5gN8B_3U0',
    appId: '1:661935203684:web:a180b01451b610059c0671',
    messagingSenderId: '661935203684',
    projectId: 'authexample-1-4b596',
    authDomain: 'authexample-1-4b596.firebaseapp.com',
    storageBucket: 'authexample-1-4b596.firebasestorage.app',
    measurementId: 'G-FSYDHR71Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMA2N8kH95r261biKNiau6UrJ29jkhw44',
    appId: '1:661935203684:android:6c11f5bdfd440ecb9c0671',
    messagingSenderId: '661935203684',
    projectId: 'authexample-1-4b596',
    storageBucket: 'authexample-1-4b596.firebasestorage.app',
  );

}